// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `angular-cli.json`.

export const environment = {
  production: false,
  memories: [
    {name: 'AUSTRIA', exit: 'AUXIT'},
    {name: 'BELGIUM', exit: 'BEXIT'},
    {name: 'BULGARIA', exit: 'BUXIT'},
    {name: 'CROATIA', exit: 'CROXIT'},
    {name: 'CYPRUS', exit: 'CYXIT'},
    {name: 'CZECH_REPUBLIC', exit: 'CZXIT'},
    {name: 'DENMARK', exit: 'DEXIT'},
    {name: 'ESTONIA', exit: 'ESTOXIT'},
    {name: 'FINNLAND', exit: 'FIXIT'},
    {name: 'FRANCE', exit: 'FRAXIT'},
    {name: 'GERMANY', exit: 'GEXIT'},
    {name: 'GREECE', exit: 'GREXIT'},
    {name: 'HUNGARY', exit: 'HUXIT'},
    {name: 'IRELAND', exit: 'IREXIT'},
    {name: 'ITALY', exit: 'ITAXIT'},
    {name: 'LATIVA', exit: 'LAXIT'},
    {name: 'LITHUANIA', exit: 'LITUXITANIA'},
    {name: 'LUXEMBOURG', exit: 'LUXIT'},
    {name: 'MALTA', exit: 'MAXIT'},
    {name: 'THE_NETHERLANDS', exit: 'DUXIT'},
    {name: 'POLAND', exit: 'POXIT'},
    {name: 'PORTUGAL', exit: 'PORXIT'},
    {name: 'ROMANIA', exit: 'ROMAXIT'},
    {name: 'SLOVAKIA', exit: 'SLOVAXITA'},
    {name: 'SLOVENIA', exit: 'SLOVIXIT'},
    {name: 'SPAIN', exit: 'ESPAXIT'},
    {name: 'SWEDEN', exit: 'SWEXIT'},
    {name: 'UNITED_KINGDOM', exit: 'BREXIT'}
  ],

  scales: {
    AUSTRIA: 90,
    AUXIT: 65,
    BELGIUM: 90,
    BEXIT: 58,
    BULGARIA: 90,
    BUXIT: 80,
    CROATIA: 90,
    CROXIT: 50,
    CYPRUS: 95,
    CYXIT: 65,
    CZECH_REPUBLIC: 90,
    CZXIT: 55,
    DENMARK: 90,
    DEXIT: 40,
    ESTONIA: 90,
    ESTOXIT: 75,
    FINNLAND: 90,
    FIXIT: 55,
    FRANCE: 90,
    FRAXIT: 60,
    GERMANY: 90,
    GEXIT: 52,
    GREECE: 92,
    GREXIT: 68,
    HUNGARY: 94,
    HUXIT: 35,
    IRELAND: 90,
    IREXIT: 53,
    ITALY: 92,
    ITAXIT: 60,
    LATIVA: 93,
    LAXIT: 80,
    LITHUANIA: 90,
    LITUXITANIA: 56,
    LUXEMBOURG: 90,
    LUXIT: 65,
    MALTA: 90,
    MAXIT: 54,
    THE_NETHERLANDS: 90,
    DUXIT: 74,
    POLAND: 90,
    POXIT: 55,
    PORTUGAL: 86,
    PORXIT: 70,
    ROMANIA: 90,
    ROMAXIT: 50,
    SLOVAKIA: 90,
    SLOVAXITA: 52,
    SLOVENIA: 90,
    SLOVIXIT: 52,
    SPAIN: 90,
    ESPAXIT: 62,
    SWEDEN: 90,
    SWEXIT: 62,
    UNITED_KINGDOM: 90,
    BREXIT: 66
  }
};
